#ifndef __TERMINAL_H__
#define __TERMINAL_H__

typedef enum Terminal { $, K_AND, K_BOOLEAN, K_DO, K_ELSE, K_ELSEIF, K_END, K_FALSE, K_FUNCTION, K_GLOBAL, K_IF, K_INTEGER, K_LOCAL, K_NIL, K_NOT, K_NUMBER, K_OR, K_REQUIRE, K_RETURN, K_STRING, K_THEN, K_TRUE, K_WHILE, T_ASS, T_COMMA, T_CONCAT, T_DEF, T_DIV, T_EQ, T_GEQ, T_GRT, T_ID, T_INT_DIV, T_INTEGER, T_LEFT, T_LEN, T_LEQ, T_LESS, T_MINUS, T_MUL, T_NEQ, T_NUMBER, T_PLUS, T_RIGHT, T_STRING} Terminal;

#endif // !__TERMINAL_H__
